name: Deploy Prod

on:
  push

jobs:
  job-CE:
    name: Edition CE
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "CE"
      - name: Check previous release
        run: |
          pwd
          ls -lah
          chmod +x .github/checkPreviousChannelRelease.sh 
          .github/checkPreviousChannelRelease.sh $MODULE_SOURCE_NAME ce $RELEASE_CHANNEL $MODULES_MODULE_TAG